// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://newmocwcwjqosxcwcfex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ld21vY3djd2pxb3N4Y3djZmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzMwMjIsImV4cCI6MjA2NzQwOTAyMn0.HK9ITvpkMEL3su6YvDxqx58tp8pcb7punquQvR0Ww-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});